backend:
  name: git-gateway
collections:
  - name: 'products'
    label: 'Products'
    folder: 'products'
    create: true
    fields:
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Is this product a best seller?', name: 'bestseller', widget: 'boolean', default: false }
      - { label: 'Category', name: 'tags', widget: 'select', options: ["Accessories", "Shoes", "Hats"] }
      - label: 'On Sale'
        name: 'onsale'
        widget: 'object'
        fields: 
          - {label: 'Is this item on sale?', name: 'sale', widget: 'boolean', default: false }
          - {label: 'Sale Price', name: 'saleprice', widget: 'string' }
      - { label: 'Details', name: 'detail', widget: 'string', default: 'Discuss with client' }
      - { label: 'Sizing', name: 'sizingimg', widget: 'image', default: '/assets/img/'}
      - { label: 'Shipping & Returns', name: 'shipReturn', widget: 'string', default: 'Discuss with client' }
      - {
        label: 'Layout',
        name: 'layout',
        widget: 'hidden',
        default: 'layouts/default.njk'
      }
 


media_folder: "/assets/img"

  